blueprint:
  name: Optimisation consommation électrique (surplus)
  description: Automation générique pour allumer/éteindre un équipement selon surplus PV
  domain: automation

  input:
    net_consumption:
      name: Consommation nette (W)
      selector:
        entity:
          domain: sensor
          device_class: power

    equipment_switch:
      name: Équipement à contrôler
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    equipment_power:
      name: Puissance consommée par l’équipement (W)
      selector:
        entity:
          domain: sensor
          device_class: power

mode: restart

trigger:
  - platform: state
    entity_id: !input net_consumption
  - platform: state
    entity_id: !input equipment_power

# Variables YAML stockant les entity_id
variables:
  net_entity: !input net_consumption
  equip_entity: !input equipment_power
  switch_entity: !input equipment_switch

condition: []

action:
  - choose:

      # 🔵 Allumer l'équipement si surproduction
      - conditions:
          - condition: numeric_state
            entity_id: !input net_consumption
            below: 0
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ switch_entity }}"

      # 🔴 Éteindre si la consommation nette dépasse l'équipement
      - conditions:
          - condition: template
            value_template: >
              {% set net = states(net_entity) | float(0) %}
              {% set equip = states(equip_entity) | float(0) %}
              {{ net > equip }}
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ switch_entity }}"
