blueprint:
  name: Optimisateur d'auto-consommation
  description: Automation générique pour allumer/éteindre lorsque la consommation nette devient négative avec gestion d'offset
  domain: automation

  input:
    net_consumption:
      name: Consommation nette (W)
      description: Consommation nette globale du foyer, la valeur doit devenir negative lorsque l'on sur-produit de l'energie.
      selector:
        entity:
          domain: sensor
          device_class: power

    equipment_switch:
      name: Équipement à piloter
      description: Équipement à piloter
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    equipment_power:
      name: Puissance consommée par l’équipement (W)
      description: Puissance instantanée consommée par l'equipement. Si vous n'avez pas pas d'appareil de mesure reelle, vous pouvez utiliser Powercal pour creer cette entité.
      selector:
        entity:
          domain: sensor
          device_class: power

    offset:
      name: Offset à l'allumage (W)
      description: Lorsque la consommation nette devient inférieure à cette valeur, l'équipement est allumé. Si vous laissez a zero, l'appareil sera allumer des que la consommation deviendra negative. Si vous regler sur 100, l'appareil sera demarrera lorsque le surplus atteindra 100W.
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          unit_of_measurement: "W"


    delay_off:
      name: Délai OFF (secondes)
      description: Temps que la consommation nette doit rester supérieure avant d'éteindre l'équipement
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          step: 1
          unit_of_measurement: "s"


mode: restart

trigger:
  # Surproduction → ON immédiat si consommation nette inférieure à l'offset
  - platform: numeric_state
    entity_id: !input net_consumption
    below: !input offset
    id: surplus_on

  # Consommation > équipement → OFF après délai paramétrable
  - platform: numeric_state
    entity_id: !input net_consumption
    above: !input equipment_power
    for:
      seconds: !input delay_off
    id: excess_off

variables:
  net_entity: !input net_consumption
  equip_entity: !input equipment_power
  switch_entity: !input equipment_switch
  delay_off_sec: !input delay_off
  offset_value: !input offset

condition: []

action:
  - choose:

      # 🔵 Allumer l'équipement si surproduction et consommation nette inférieure à l'offset
      - conditions:
          - condition: trigger
            id: surplus_on
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ switch_entity }}"

      # 🔴 Éteindre si consommation nette > équipement et délai OFF
      - conditions:
          - condition: trigger
            id: excess_off
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ switch_entity }}"


