blueprint:
  name: Optimisation consommation électrique (surplus) avec hystérésis
  description: Automation générique pour allumer/éteindre un équipement selon surplus PV, avec hystérésis et délai ON/OFF
  domain: automation

  input:
    net_consumption:
      name: Consommation nette (W)
      selector:
        entity:
          domain: sensor
          device_class: power

    equipment_switch:
      name: Équipement à contrôler
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    equipment_power:
      name: Puissance consommée par l’équipement (W)
      selector:
        entity:
          domain: sensor
          device_class: power

    hysteresis:
      name: Hystérésis (W)
      description: Marge pour éviter les allumages/extinctions trop rapides
      default: 50
      selector:
        number:
          min: 0
          max: 500
          step: 10
          unit_of_measurement: "W"

    delay_on:
      name: Délai ON (secondes)
      default: 5
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: "s"

    delay_off:
      name: Délai OFF (secondes)
      default: 5
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: "s"

mode: restart

trigger:
  - platform: state
    entity_id: !input net_consumption
  - platform: state
    entity_id: !input equipment_power

variables:
  net_entity: !input net_consumption
  equip_entity: !input equipment_power
  switch_entity: !input equipment_switch
  hyst: !input hysteresis
  delay_on_sec: !input delay_on
  delay_off_sec: !input delay_off

condition: []

action:
  - choose:

      # 🔵 Allumer l'équipement si surproduction + hystérésis
      - conditions:
          - condition: template
            value_template: >
              {% set net = states(net_entity) | float(0) %}
              {% set equip = states(equip_entity) | float(0) %}
              {{ net < -hyst }}
        sequence:
          - delay:
              seconds: "{{ delay_on_sec }}"
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ switch_entity }}"

      # 🔴 Éteindre si consommation nette dépasse puissance + hystérésis
      - conditions:
          - condition: template
            value_template: >
              {% set net = states(net_entity) | float(0) %}
              {% set equip = states(equip_entity) | float(0) %}
              {{ net > equip + hyst }}
        sequence:
          - delay:
              seconds: "{{ delay_off_sec }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ switch_entity }}"
