blueprint:
  name: Optimisation consommation électrique (surplus) avec hystérésis et délai OFF
  description: Automation générique pour allumer/éteindre un équipement selon surplus PV, avec hystérésis et délai OFF basé sur la consommation
  domain: automation

  input:
    net_consumption:
      name: Consommation nette (W)
      selector:
        entity:
          domain: sensor
          device_class: power

    equipment_switch:
      name: Équipement à contrôler
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    equipment_power:
      name: Puissance consommée par l’équipement (W)
      selector:
        entity:
          domain: sensor
          device_class: power

    hysteresis:
      name: Hystérésis (W)
      description: Marge pour éviter les allumages/extinctions trop rapides
      default: 50
      selector:
        number:
          min: 0
          max: 500
          step: 10
          unit_of_measurement: "W"

    delay_off:
      name: Délai OFF (secondes)
      description: Temps que la consommation nette doit rester supérieure à l'équipement pour éteindre
      default: 5
      selector:
        number:
          min: 0
          max: 600
          step: 1
          unit_of_measurement: "s"

mode: restart

trigger:
  # Surproduction → ON immédiat
  - platform: numeric_state
    entity_id: !input net_consumption
    below: 0
    id: surplus_on

  # Consommation > équipement → OFF après délai paramétrable
  - platform: numeric_state
    entity_id: !input net_consumption
    above: !input equipment_power
    for:
      seconds: !input delay_off
    id: excess_off

variables:
  net_entity: !input net_consumption
  equip_entity: !input equipment_power
  switch_entity: !input equipment_switch
  hyst: !input hysteresis
  delay_off_sec: !input delay_off

condition: []

action:
  - choose:

      # 🔵 Allumer l'équipement si surproduction + hystérésis
      - conditions:
          - condition: trigger
            id: surplus_on
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ switch_entity }}"

      # 🔴 Éteindre si consommation nette > équipement + hystérésis et délai OFF
      - conditions:
          - condition: trigger
            id: excess_off
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ switch_entity }}"
