blueprint:
  name: Optimisation consommation électrique (surplus)
  description: >
    Allume un équipement lorsque la consommation nette devient négative (surproduction),
    et l'éteint lorsque la consommation nette dépasse la puissance de l'équipement.
  domain: automation

  input:
    net_consumption:
      name: Consommation nette du foyer (W)
      selector:
        entity:
          domain: sensor
          device_class: power

    equipment_switch:
      name: Équipement à contrôler
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    equipment_power:
      name: Puissance consommée par l’équipement (W)
      selector:
        entity:
          domain: sensor
          device_class: power

mode: restart

trigger:
  - platform: state
    entity_id: !input net_consumption

  - platform: state
    entity_id: !input equipment_power

condition: []

action:
  - choose:

      # 🔵 SURPRODUCTION → ON
      - conditions:
          - condition: numeric_state
            entity_id: !input net_consumption
            below: 0
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input equipment_switch

      # 🔴 CONSOMMATION NETTE > PUISSANCE → OFF
      - conditions:
          - condition: template
            value_template: >
              {{ states(inputs.net_consumption) | float > 
                 states(inputs.equipment_power) | float }}
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input equipment_switch
