blueprint:
  name: Chauffe-eau intelligent – CE simulés
  description: Gère un chauffe-eau avec préchauffage HC, surplus solaire et extinction automatique
  domain: automation
  input:

    # Switch du CE simulé
    ce_switch:
      name: Switch du chauffe-eau
      selector:
        entity:
          domain: input_boolean
      default: input_boolean.ce1_switch

    # Capteur d'énergie du CE simulé
    ce_energy_sensor:
      name: Capteur d'énergie du CE (kWh)
      selector:
        entity:
          domain: input_number
      default: input_number.ce1_energy

    # Capteur de surplus solaire simulé
    surplus_sensor:
      name: Capteur de surplus PV (W)
      selector:
        entity:
          domain: input_number
      default: input_number.surplus_ce1

    # Capteur de prévision solaire simulé
    forecast_sensor:
      name: Capteur de prévision solaire (kWh)
      selector:
        entity:
          domain: input_number
      default: input_number.solar_ce1

    forecast_min:
      name: Seuil minimum de prévision solaire (kWh)
      default: 3
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: kWh

    ce_power:
      name: Puissance nominale du CE (kW)
      default: 2
      selector:
        number:
          min: 0.5
          max: 6
          step: 0.1
          unit_of_measurement: kW

    min_duration:
      name: Surplus minimum stable (minutes)
      default: 3
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: min

    off_delay:
      name: Durée avant extinction si plus de surplus (minutes)
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: min

    # Heure de fin HC
    hc_end_time:
      name: Heure de fin des heures creuses
      default: "06:00"
      selector:
        time: {}

    history_days:
      name: Nombre de jours pour calcul historique
      default: 7
      selector:
        number:
          min: 1
          max: 30
          step: 1

    priority:
      name: Priorité CE (production solaire uniquement)
      default: 1
      selector:
        number:
          min: 1
          max: 10
          step: 1

mode: restart
max_exceeded: silent

trigger:
  - platform: time
    at: "00:00:00"
  - platform: state
    entity_id: !input surplus_sensor
  - platform: time
    at: !input hc_end_time

variables:
  ce_switch: !input ce_switch
  ce_energy_sensor: !input ce_energy_sensor
  surplus_sensor: !input surplus_sensor
  ce_power: !input ce_power
  min_duration: !input min_duration
  off_delay: !input off_delay
  hc_end_time: !input hc_end_time
  history_days: !input history_days
  priority: !input priority
  forecast_sensor: !input forecast_sensor
  forecast_min: !input forecast_min

action:
  # 1️⃣ Calcul consommation moyenne et durée préchauffage HC
  - variables:
      total_energy: "{{ states(ce_energy_senso_
