blueprint:
  name: Chauffe-eau intelligent – préchauffage HC + surplus solaire
  description: >
    Chauffe-eau intelligent basé sur :
    - Surplus solaire
    - Historique des derniers jours pour estimer la consommation
    - Pré-chauffage durant les heures creuses
  domain: automation
  input:

    # Capteurs et switch
    ce_switch:
      name: Switch du chauffe-eau
      selector:
        entity:
          domain: switch

    ce_energy_sensor:
      name: Capteur d'énergie du chauffe-eau (kWh)
      description: Capteur historique de consommation du CE
      selector:
        entity:
          domain: sensor

    surplus_sensor:
      name: Capteur de surplus PV (W)
      selector:
        entity:
          domain: sensor

    forecast_sensor:
      name: Capteur de prévision solaire (kWh)
      description: Prévision pour aujourd'hui (optionnel si on veut prédiction)
      selector:
        entity:
          domain: sensor

    forecast_min:
      name: Seuil minimum de prévision solaire (kWh)
      default: 3
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: kWh

    # Paramètres calcul
    ce_power:
      name: Puissance nominale du CE (kW)
      description: Valeur utilisée si pas de consommation réelle
      default: 2
      selector:
        number:
          min: 0.5
          max: 6
          step: 0.1
          unit_of_measurement: kW

    min_duration:
      name: Surplus minimum stable (minutes)
      default: 3
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: min

    off_delay:
      name: Durée avant extinction si plus de surplus (minutes)
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: min

    hc_end_time:
      name: Heure de fin des heures creuses
      default: "06:00"
      selector:
        time: {}

    history_days:
      name: Nombre de jours pour calcul historique
      default: 7
      selector:
        number:
          min: 1
          max: 30
          step: 1

mode: restart
max_exceeded: silent

trigger:
  - platform: time
    at: "00:00:00"  # Recalcul quotidien
  - platform: state
    entity_id: !input surplus_sensor
  - platform: time
    at: !input hc_end_time

variables:
  ce_energy_sensor: !input ce_energy_sensor
  surplus_sensor: !input surplus_sensor
  ce_switch: !input ce_switch
  ce_power: !input ce_power
  min_duration: !input min_duration
  off_delay: !input off_delay
  hc_end_time: !input hc_end_time
  history_days: !input history_days

action:

  # 1️⃣ Calcul de la consommation moyenne quotidienne
  - variables:
      total_energy: >
        {{ (states(ce_energy_sensor)|float) }}  # si tu veux, on peut faire average historique réel
      avg_daily_energy: >
        {{ total_energy / history_days | float }}

      # Calcul du temps de préchauffage nécessaire (minutes)
      preheat_duration: >
        {{ ((avg_daily_energy) / ce_power * 60) | round(0) }}

      # Heure de démarrage du préchauffage
      hc_end_hour: "{{ hc_end_time.split(':')[0] | int }}"
      hc_end_minute: "{{ hc_end_time.split(':')[1] | int }}"
      hc_end_total_min: "{{ hc_end_hour * 60 + hc_end_minute }}"
      preheat_start_min: "{{ hc_end_total_min - preheat_duration }}"
      preheat_start_hour: "{{ (preheat_start_min // 60) | int }}"
      preheat_start_minute: "{{ (preheat_start_min % 60) | int }}"

  # 2️⃣ Planifier le préchauffage HC
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ preheat_duration > 0 }}"
        sequence:
          - delay_until:
              # Calcul du moment exact pour démarrer le préchauffage
              datetime: "{{ now().replace(hour=preheat_start_hour,minute=preheat_start_minute,second=0) }}"
          - service: switch.turn_on
            target:
              entity_id: !input ce_switch
          - delay:
              minutes: "{{ preheat_duration }}"
          - service: switch.turn_off
            target:
              entity_id: !input ce_switch

  # 3️⃣ Gestion normale par surplus solaire (après HC)
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input surplus_sensor
            above: !input min_duration
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input ce_switch
      - conditions:
          - condition: numeric_state
            entity_id: !input surplus_sensor
            below: 0
        sequence:
          - delay: "00:{{ off_delay }}"
          - service: switch.turn_off
            target:
              entity_id: !input ce_switch
