blueprint:
  name: Optimisation consommation électrique (surplus)
  description: >
    Allume l'équipement quand la consommation nette est négative et l'éteint
    lorsqu'elle dépasse la consommation de l'appareil.
  domain: automation

  input:
    net_consumption:
      name: Consommation nette (W)
      selector:
        entity:
          domain: sensor
          device_class: power

    equipment_switch:
      name: Équipement à contrôler
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    equipment_power:
      name: Puissance de l'équipement (W)
      selector:
        entity:
          domain: sensor
          device_class: power

mode: restart

trigger:
  - platform: state
    entity_id: !input net_consumption

  - platform: state
    entity_id: !input equipment_power

condition: []

action:
  - choose:

      # 🔵 SURPRODUCTION → ON
      - conditions:
          - condition: numeric_state
            entity_id: !input net_consumption
            below: 0
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input equipment_switch

      # 🔴 PAS ASSEZ DE SURPLUS → OFF
      - conditions:
          - condition: template
            value_template: >
              {% set net_id = inputs.net_consumption %}
              {% set equip_id = inputs.equipment_power %}
              {% set net = states(net_id) | float(0) %}
              {% set equip = states(equip_id) | float(0) %}
              {{ net > equip }}
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input equipment_switch
