blueprint:
  name: Optimisation consommation électrique (surplus)
  description: >
    Allume un équipement quand la consommation nette du foyer devient négative
    et l'éteint lorsque la consommation nette dépasse la consommation de l'équipement.
  domain: automation
  input:
    net_consumption:
      name: Consommation nette du foyer (W)
      description: Capteur indiquant la consommation nette (négatif = surplus)
      selector:
        entity:
          domain: sensor
          device_class: power

    equipment_switch:
      name: Équipement à contrôler
      description: Input_boolean ou switch qui commande l’équipement
      selector:
        entity:
          domain: 
            - switch
            - input_boolean

    equipment_power:
      name: Puissance consommée par l’équipement (W)
      description: Capteur powercalc représentant la consommation de l'appareil
      selector:
        entity:
          domain: sensor
          device_class: power

mode: restart

trigger:
  - platform: state
    entity_id: !input net_consumption
  - platform: state
    entity_id: !input equipment_power

condition: []

action:
  - choose:

      # 🔵 SURPRODUCTION : consommation nette < 0 → ON
      - conditions:
          - condition: numeric_state
            entity_id: !input net_consumption
            below: 0
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input equipment_switch

      # 🔴 CONSOMMATION NETTE > CONSO APPAREIL → OFF
      - conditions:
          - condition: template
            value_template: >
              {{ states( !input net_consumption ) | float >
                 states( !input equipment_power ) | float }}
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input equipment_switch

