blueprint:
  name: Chauffe-eau intelligent multi-CE – HC + surplus solaire avec priorité
  description: >
    Gère plusieurs chauffe-eau intelligemment :
    - Pré-chauffage pendant les heures creuses selon consommation historique
    - Gestion du surplus solaire avec priorité pour éviter les collisions
  domain: automation
  input:

    # Switch du CE
    ce_switch:
      name: Switch du chauffe-eau
      selector:
        entity:
          domain: switch

    # Capteur d'énergie du CE (historique)
    ce_energy_sensor:
      name: Capteur d'énergie du CE (kWh)
      description: Capteur historique pour estimer consommation
      selector:
        entity:
          domain: sensor

    # Capteur de surplus solaire
    surplus_sensor:
      name: Capteur de surplus PV (W)
      selector:
        entity:
          domain: sensor

    # Capteur de prévision solaire
    forecast_sensor:
      name: Capteur de prévision solaire (kWh)
      description: Prévision pour aujourd'hui (optionnel)
      default: sensor.energy_production_today
      selector:
        entity:
          domain: sensor

    forecast_min:
      name: Seuil minimum de prévision solaire (kWh)
      default: 3
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: kWh

    # Paramètres de calcul
    ce_power:
      name: Puissance nominale du CE (kW)
      description: Utilisée si pas de capteur historique
      default: 2
      selector:
        number:
          min: 0.5
          max: 6
          step: 0.1
          unit_of_measurement: kW

    min_duration:
      name: Surplus minimum stable (minutes)
      default: 3
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: min

    off_delay:
      name: Durée avant extinction si plus de surplus (minutes)
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: min

    # Heure de fin HC
    hc_end_time:
      name: Heure de fin des heures creuses
      default: "06:00"
      selector:
        time: {}

    # Historique pour calcul consommation
    history_days:
      name: Nombre de jours pour calcul historique
      default: 7
      selector:
        number:
          min: 1
          max: 30
          step: 1

    # Priorité pendant surplus solaire
    priority:
      name: Priorité CE (production solaire uniquement)
      description: Plus le nombre est bas, plus le CE a priorité haute
      default: 1
      selector:
        number:
          min: 1
          max: 10
          step: 1

mode: restart
max_exceeded: silent

trigger:
  # Recalcul quotidien
  - platform: time
    at: "00:00:00"
  # Changement du surplus PV
  - platform: state
    entity_id: !input surplus_sensor
  # Fin des heures creuses
  - platform: time
    at: !input hc_end_time

variables:
  ce_switch: !input ce_switch
  ce_energy_sensor: !input ce_energy_sensor
  surplus_sensor: !input surplus_sensor
  ce_power: !input ce_power
  min_duration: !input min_duration
  off_delay: !input off_delay
  hc_end_time: !input hc_end_time
  history_days: !input history_days
  priority: !input priority

action:

  # 1️⃣ Calcul consommation moyenne et durée préchauffage HC
  - variables:
      total_energy: "{{ states(ce_energy_sensor)|float }}"
      avg_daily_energy: "{{ total_energy / history_days | float }}"
      preheat_duration: "{{ ((avg_daily_energy) / ce_power * 60) | round(0) }}"
      hc_end_hour: "{{ hc_end_time.split(':')[0] | int }}"
      hc_end_minute: "{{ hc_end_time.split(':')[1] | int }}"
      hc_end_total_min: "{{ hc_end_hour * 60 + hc_end_minute }}"
      preheat_start_min: "{{ hc_end_total_min - preheat_duration }}"
      preheat_start_hour: "{{ (preheat_start_min // 60) | int }}"
      preheat_start_minute: "{{ (preheat_start_min % 60) | int }}"

  # 2️⃣ Pré-chauffage HC (tous les CE déclenchent indépendamment)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ preheat_duration > 0 }}"
        sequence:
          - delay_until:
              datetime: "{{ now().replace(hour=preheat_start_hour,minute=preheat_start_minute,second=0) }}"
          - service: switch.turn_on
            target:
              entity_id: !input ce_switch
          - delay:
              minutes: "{{ preheat_duration }}"
          - service: switch.turn_off
            target:
              entity_id: !input ce_switch

  # 3️⃣ Surplus solaire avec priorités
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input surplus_sensor
            above: !input min_duration
        sequence:
          - variables:
              surplus_available: "{{ states(surplus_sensor) | float }}"
          - choose:
              - conditions: "{{ surplus_available >= ce_power }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input ce_switch
                  - variables:
                      surplus_available: "{{ surplus_available - ce_power }}"
              - default:
                  - service: switch.turn_off
                    target:
                      entity_id: !input ce_switch

      - conditions:
          - condition: numeric_state
            entity_id: !input surplus_sensor
            below: 0
        sequence:
          - delay: "00:{{ off_delay }}"
          - service: switch.turn_off
            target:
              entity_id: !input ce_switch
