blueprint:
  name: Optimisation consommation électrique (surplus)
  description: >
    Allume un équipement quand la consommation nette du foyer devient négative
    (surproduction), et l'éteint lorsque la consommation nette dépasse
    la consommation de l'équipement.
  domain: automation
  input:
    net_consumption:
      name: Consommation nette du foyer (W)
      description: Capteur indiquant la consommation nette (négatif = surplus)
      selector:
        entity:
          domain: sensor
          device_class: power

    equipment_switch:
      name: Équipement à contrôler
      description: Input_boolean ou switch qui commande l’équipement
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    equipment_power:
      name: Puissance consommée par l’équipement (W)
      description: Capteur powercalc représentant la consommation de l'appareil
      selector:
        entity:
          domain: sensor
          device_class: power

mode: restart

trigger:
  - platform: state
    entity_id: !input net_consumption
  - platform: state
    entity_id: !input equipment_power

condition: []

action:
  - choose:

      # 1) SURPRODUCTION : consommation nette < 0 → ON
      - conditions:
          - condition: numeric_state
            entity_id: !input net_consumption
            below: 0
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input equipment_switch

      # 2) PAS ASSEZ DE SURPLUS → OFF (consommation_nette > conso_appareil)
      - conditions:
          - condition: template
            # IMPORTANT : utiliser !input 'name' ENTRE APOSTROPHES dans le template
            value_template: >
              {% set net = states( !input 'net_consumption' ) %}
              {% set equip = states( !input 'equipment_power' ) %}
              {{ (net | float(0)) > (equip | float(0)) }}
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input equipment_switch
